routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('invoices', 'InvoicesController');
    Route::get('invoices/{invoice_id}/download', 'InvoicesController@download')->name('invoices.download');
    Route::resource('customers', 'CustomerController');
    Route::resource('products', 'ProductController');
});

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = ['invoice_number', 'invoice_date', 'customer_id', 'tax_percent'];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function invoice_items()
    {
        return $this->hasMany(InvoiceItem::class);
    }

    public function getTotalAmountAttribute()
    {
        $total_amount = 0;
        foreach ($this->invoice_items as $item) {
            $total_amount += $item->price * $item->quantity;
        }
        return $total_amount;
    }
}

app/Http/Controllers/InvoicesController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\CustomerField;
use App\Invoice;
use App\InvoiceItem;
use App\Product;
use Illuminate\Http\Request;

class InvoicesController extends Controller
{
    public function create()
    {
        $customers = Customer::all();
        $products = Product::all();
        return view('invoices.create', compact('customers', 'products'));
    }

    public function store(Request $request)
    {

        $invoice = Invoice::create($request->invoice);

        for ($i = 0; $i < count($request->product); $i++) {
            if (isset($request->qty[$i]) && isset($request->price[$i])) {
                InvoiceItem::create([
                    'invoice_id' => $invoice->id,
                    'name' => $request->product[$i],
                    'quantity' => $request->qty[$i],
                    'price' => $request->price[$i],
                ]);
            }
        }

        return redirect(route('home'));
    }

    public function show($invoice_id)
    {
        $invoice = Invoice::findOrFail($invoice_id);
        return view('invoices.show', compact('invoice'));
    }

    public function download($invoice_id)
    {
        $invoice = Invoice::findOrFail($invoice_id);
        $pdf = \PDF::loadView('invoices.pdf', compact('invoice'));

        return $pdf->stream('invoice.pdf');
    }
}

resources/views/invoices/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Invoice</div>
                <form action="{{ route('invoices.store') }}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="container">
                            <div class="row clearfix">
                                <div class="col-md-4 offset-4 text-center">
                                    Invoice Number*:
                                    <br />
                                    <input type="text" name="invoice[invoice_number]" class="form-control" placeholder="AA001" required />
                                    Invoice Date*:
                                    <br />
                                    <input type="text" name="invoice[invoice_date]" class="form-control" value="{{ date('Y-m-d') }}" required />
                                </div>
                            </div>

                            <div class="row clearfix" style="margin-top: 20px">
                                <div class="col-md-12">
                                    <div class="float-left">
                                        <b>Choose details</b><br />
                                        <select name="invoice[customer_id]" class="form-control">
                                            @foreach($customers as $customer)
                                            <option value="{{ $customer->id }}">{{ $customer->name }}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                    <div class="float-right col-md-4">
                                        <b>Seller Details</b>
                                        <br /><br />
                                        Your company name
                                        <br />
                                        1 Street Name, London, United Kingdom
                                        <br />
                                        Email: xxxx@company.com
                                        <br />
                                        VAT Number: xx xxxxx xxxx
                                    </div>
                                </div>
                            </div>

                            <div class="row clearfix ">
                                <div class="col-md-12">
                                    <table class="table table-bordered table-hover" id="tab_logic">
                                        <thead>
                                            <tr>
                                                <th class="text-center"> # </th>
                                                <th class="text-center"> Product </th>
                                                <th class="text-center"> Qty </th>
                                                <th class="text-center"> Price </th>
                                                <th class="text-center"> Total </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr id='addr0'>
                                                <td>1</td>
                                                <td>
                                                    <select name="[]" class="form-control">
                                                        @foreach($products as $product)
                                                        <option value="{{ $product->id }}">{{ $product->name }}</option>
                                                        @endforeach
                                                    </select>
                                                    <!-- <input type="text" name='product[]' placeholder='Enter Product Name' class="form-control" /> -->
                                                </td>
                                                <td><input type="number" name='qty[]' placeholder='Enter Qty' class="form-control qty" step="0" min="0" /></td>
                                                <td><input type="number" name='price[]' placeholder='Enter Unit Price' class="form-control price" step="0.00" min="0" /></td>
                                                <td><input type="number" name='total[]' placeholder='0.00' class="form-control total" readonly /></td>
                                            </tr>
                                            <tr id='addr1'></tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row clearfix">
                                <div class="col-md-12">
                                    <button id="add_row" class="btn btn-primary float-left">Add Row</button>
                                    <button id='delete_row' class="float-right btn btn-info">Delete Row</button>
                                </div>
                            </div>
                            <div class="row clearfix" style="margin-top:20px">
                                <div class="col-md-12">
                                    <div class="float-right col-md-6">
                                        <table class="table table-bordered table-hover" id="tab_logic_total">
                                            <tbody>
                                                <tr>
                                                    <th class="text-center">Sub Total</th>
                                                    <td class="text-center"><input type="number" name='sub_total' placeholder='0.00' class="form-control" id="sub_total" readonly /></td>
                                                </tr>
                                                <tr>
                                                    <th class="text-center">Tax</th>
                                                    <td class="text-center">
                                                        <div class="input-group mb-2 mb-sm-0">
                                                            <input type="number" class="form-control" id="tax" placeholder="0" name="invoice[tax_percent]" />
                                                            <div class="input-group-addon">%</div>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th class="text-center">Tax Amount</th>
                                                    <td class="text-center"><input type="number" name='tax_amount' id="tax_amount" placeholder='0.00' class="form-control" readonly /></td>
                                                </tr>
                                                <tr>
                                                    <th class="text-center">Grand Total</th>
                                                    <td class="text-center"><input type="number" name='total_amount' id="total_amount" placeholder='0.00' class="form-control" readonly /></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-primary">Save Invoice</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        var i = 1;
        $("#add_row").click(function() {
            b = i - 1;
            $('#addr' + i).html($('#addr' + b).html()).find('td:first-child').html(i + 1);
            $('#tab_logic').append('<tr id="addr' + (i + 1) + '"></tr>');
            i++;
        });
        $("#delete_row").click(function() {
            if (i > 1) {
                $("#addr" + (i - 1)).html('');
                i--;
            }
            calc();
        });

        $('#tab_logic tbody').on('keyup change', function() {
            calc();
        });
        $('#tax').on('keyup change', function() {
            calc_total();
        });


    });

    function calc() {
        $('#tab_logic tbody tr').each(function(i, element) {
            var html = $(this).html();
            if (html != '') {
                var qty = $(this).find('.qty').val();
                var price = $(this).find('.price').val();
                $(this).find('.total').val(qty * price);

                calc_total();
            }
        });
    }

    function calc_total() {
        total = 0;
        $('.total').each(function() {
            total += parseInt($(this).val());
        });
        $('#sub_total').val(total.toFixed(2));
        tax_sum = total / 100 * $('#tax').val();
        $('#tax_amount').val(tax_sum.toFixed(2));
        $('#total_amount').val((tax_sum + total).toFixed(2));
    }
</script>
@endsection

resources/views/invoices/pdf.blade.php
@extends('layouts.pdf')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Invoice Number: {{ $invoice->invoice_number }}</div>

                <div class="card-body">
                    <div class="container">
                        <div class="row clearfix">
                            @if(config('invoices.logo_file'))
                            <div class="col-md-12 text-center">
                                <img src="{{ config('invoices.logo_file') }}" width="250px" />
                            </div>
                            @endif
                        </div>

                        <div class="row clearfix">
                            <div class="col-md-4 offset-4 text-center">
                                <b>Invoice: {{ $invoice->invoice_number }}</b>
                                <br />
                                {{ $invoice->invoice_date }}
                            </div>
                        </div>

                        <div class="row clearfix" style="margin-top: 20px">
                            <div class="col-md-12">
                                <div class="float-left">
                                    <b>To</b>
                                    <br /><br />
                                    <b>Address</b>
                                    {{ $invoice->customer->address }}
                                    @if($invoice->customer->postcode != '')
                                    , {{ $invoice->customer->postcode }}
                                    @endif
                                    , {{ $invoice->customer->city}}
                                    @if($invoice->customer->state != '')
                                    , {{ $invoice->customer->state }}
                                    @endif
                                    , {{ $invoice->customer->country }}
                                    @if($invoice->customer->phone != '')
                                    <br /><br /><b>Phone</b>: {{ $invoice->customer->phone }}
                                    @endif
                                    @if($invoice->customer->email != '')
                                    <br /><br /><b>Phone</b>: {{ $invoice->customer->email }}
                                    @endif
                                    @if($invoice->customer->customer_fields)
                                    @foreach($invoice->customer->customer_fields as $field)
                                    <br /><br /><br />{{ $field->field_key }}<b>: {{ $field->field_value }}
                                        @endforeach
                                        @endif
                                </div>
                                <div class="float-right col-md-4">
                                    <b>From</b>: {{ config('invoices.seller.name') }}
                                    <br /><br />
                                    <b>Address</b>: {{ config('invoices.seller.address') }}
                                    @if(config('invoices.seller.email') != '')
                                    <br><br>
                                    <b>Email</b>: {{config('invoices.seller.email') }}
                                    @endif
                                    @if(is_array(config('invoices.seller.additional_info')))
                                    @foreach(config('invoices.seller.additional_info') as $key=>$value)
                                    <br>
                                    <b>{{ $key }}</b>: {{ $value }}
                                    @endforeach
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix ">
                            <div class="col-md-12">
                                <table class="table table-bordered table-hover" id="tab_logic">
                                    <thead>
                                        <tr>
                                            <th class="text-center"> # </th>
                                            <th class="text-center"> Product </th>
                                            <th class="text-center"> Qty </th>
                                            <th class="text-center"> Price </th>
                                            <th class="text-center"> Total </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($invoice->invoice_items as $item)
                                        <tr id='addr0'>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->quantity }}</td>
                                            <td>{{ $item->price }}</td>
                                            <td>{{number_format($item->quantity * $item->price, 2) }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="row clearfix" style="margin-top:20px">
                            <div class="col-md-12">
                                <div class="float-right col-md-6">
                                    <table class="table table-bordered table-hover tbl-total" id="tab_logic_total">
                                        <tbody>
                                            <tr>
                                                <th class="text-center">Sub Total</th>
                                                <td class="text-center">{{ number_format($invoice->total_amount, 2) }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Tax</th>
                                                <td class="text-center">{{ $invoice->tax_percent }}%</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Tax Amount</th>
                                                <td class="text-center">{{ number_format(($invoice->total_amount * $invoice->tax_percent) / 100, 2) }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Grand Total</th>
                                                <td class="text-center">{{ number_format(($invoice->total_amount + ($invoice->total_amount * $invoice->tax_percent) / 100), 2) }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-12">
                                {{config('invoices.footer_text')}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/invoices/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Invoice Number: {{ $invoice->invoice_number }}</div>

                <div class="card-body">
                    <div class="container">
                        <div class="row clearfix">
                            @if(config('invoices.logo_file'))
                            <div class="col-md-12 text-center">
                                <img src="{{ config('invoices.logo_file') }}" width="250px" />
                            </div>
                            @endif
                        </div>

                        <div class="row clearfix">
                            <div class="col-md-4 offset-4 text-center">
                                <b>Invoice: {{ $invoice->invoice_number }}</b>
                                <br />
                                {{ $invoice->invoice_date }}
                            </div>
                        </div>

                        <div class="row clearfix" style="margin-top: 20px">
                            <div class="col-md-12">
                                <div class="float-left">
                                    <b>To</b>
                                    <br /><br />
                                    <b>Address</b>
                                    {{ $invoice->customer->address }}
                                    @if($invoice->customer->postcode != '')
                                    , {{ $invoice->customer->postcode }}
                                    @endif
                                    , {{ $invoice->customer->city}}
                                    @if($invoice->customer->state != '')
                                    , {{ $invoice->customer->state }}
                                    @endif
                                    , {{ $invoice->customer->country }}
                                    @if($invoice->customer->phone != '')
                                    <br /><br /><b>Phone</b>: {{ $invoice->customer->phone }}
                                    @endif
                                    @if($invoice->customer->email != '')
                                    <br /><br /><b>Phone</b>: {{ $invoice->customer->email }}
                                    @endif
                                    @if($invoice->customer->customer_fields)
                                    @foreach($invoice->customer->customer_fields as $field)
                                    <br /><br /><br />{{ $field->field_key }}<b>: {{ $field->field_value }}
                                        @endforeach
                                        @endif
                                </div>
                                <div class="float-right col-md-4">
                                    <b>From</b>: {{ config('invoices.seller.name') }}
                                    <br /><br />
                                    <b>Address</b>: {{ config('invoices.seller.address') }}
                                    @if(config('invoices.seller.email') != '')
                                    <br><br>
                                    <b>Email</b>: {{config('invoices.seller.email') }}
                                    @endif
                                    @if(is_array(config('invoices.seller.additional_info')))
                                    @foreach(config('invoices.seller.additional_info') as $key=>$value)
                                    <br>
                                    <b>{{ $key }}</b>: {{ $value }}
                                    @endforeach
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix ">
                            <div class="col-md-12">
                                <table class="table table-bordered table-hover" id="tab_logic">
                                    <thead>
                                        <tr>
                                            <th class="text-center"> # </th>
                                            <th class="text-center"> Product </th>
                                            <th class="text-center"> Qty </th>
                                            <th class="text-center"> Price </th>
                                            <th class="text-center"> Total </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($invoice->invoice_items as $item)
                                        <tr id='addr0'>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->quantity }}</td>
                                            <td>{{ $item->price }}</td>
                                            <td>{{number_format($item->quantity * $item->price, 2) }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="row clearfix" style="margin-top:20px">
                            <div class="col-md-12">
                                <div class="float-right col-md-6">
                                    <table class="table table-bordered table-hover" id="tab_logic_total">
                                        <tbody>
                                            <tr>
                                                <th class="text-center">Sub Total</th>
                                                <td class="text-center">{{ number_format($invoice->total_amount, 2) }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Tax</th>
                                                <td class="text-center">{{ $invoice->tax_percent }}%</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Tax Amount</th>
                                                <td class="text-center">{{ number_format(($invoice->total_amount * $invoice->tax_percent) / 100, 2) }}</td>
                                            </tr>
                                            <tr>
                                                <th class="text-center">Grand Total</th>
                                                <td class="text-center">{{ number_format(($invoice->total_amount + ($invoice->total_amount * $invoice->tax_percent) / 100), 2) }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-md-12">
                                {{config('invoices.footer_text')}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection